package com.moneyfamily.app

import android.app.DatePickerDialog
import android.content.Context
import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.Canvas
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.unit.dp
import com.moneyfamily.app.data.Movement
import com.moneyfamily.app.data.MovementType
import kotlinx.coroutines.launch
import org.json.JSONArray
import org.json.JSONObject
import java.text.NumberFormat
import java.text.SimpleDateFormat
import java.util.Calendar
import java.util.Date
import java.util.Locale

private val money=NumberFormat.getCurrencyInstance(Locale.ITALY)
private val dateFormat=SimpleDateFormat("dd/MM/yyyy",Locale.ITALY)
private val monthFormat=SimpleDateFormat("MMMM yyyy",Locale.ITALIAN)
private val expenseCategories=listOf("Alimentari","Casa","Auto","Bollette","Salute","Figli","Istruzione","Abbigliamento","Tempo libero","Vacanze","Sport","Altro")
private val incomeCategories=listOf("Stipendio","Bonus","Rimborso","Altro")
private val paymentMethods=listOf("Contanti","Carta","Bonifico","Addebito","Altro")
private const val PREFS="moneyfamily_data"
private const val RECORDS="records"
private const val MEMBERS="members"

enum class RecordType{EXPENSE,INCOME}
data class MoneyRecord(val id:Long,val type:RecordType,val amount:Double,val category:String,val description:String,val date:String,val member:String,val paymentMethod:String)

class MainActivity:ComponentActivity(){override fun onCreate(b:Bundle?){super.onCreate(b);setContent{MoneyFamilyApp()}}}

@Composable private fun MoneyFamilyApp(){
 val context=LocalContext.current;val prefs=remember{context.getSharedPreferences(PREFS,Context.MODE_PRIVATE)};val repo=remember{com.moneyfamily.app.data.RoomRepository(context)};val scope=rememberCoroutineScope()
 var list by remember{mutableStateOf(loadRecords(prefs))};var members by remember{mutableStateOf(loadMembers(prefs).ifEmpty{listOf("Famiglia","Papà","Mamma","Figlio 1","Figlio 2")})};var tab by remember{mutableStateOf(0)};var month by remember{mutableStateOf(Calendar.getInstance())};var editor by remember{mutableStateOf<MoneyRecord?>(null)};var adding by remember{mutableStateOf(false)};var roomReady by remember{mutableStateOf(false)}
 LaunchedEffect(Unit){runCatching{repo.all()}.onSuccess{stored->if(stored.isNotEmpty())list=stored.map{it.toUi()} else list.forEach{repo.insert(it.toMovement())};roomReady=true}}
 fun save(item:MoneyRecord){val existed=list.any{it.id==item.id};list=if(existed)list.map{if(it.id==item.id)item else it}else listOf(item)+list;saveRecords(prefs,list);if(roomReady)scope.launch{if(existed)repo.update(item.toMovement())else repo.insert(item.toMovement())}}
 val current=list.filter{sameMonth(it.date,month)};val income=current.filter{it.type==RecordType.INCOME}.sumOf{it.amount};val expense=current.filter{it.type==RecordType.EXPENSE}.sumOf{it.amount};val label=monthFormat.format(month.time).replaceFirstChar{it.uppercase()}
 MaterialTheme{Scaffold(bottomBar={NavigationBar{listOf("Home","Movimenti","Analisi","Impostazioni").forEachIndexed{i,title->NavigationBarItem(tab==i,{tab=i},icon={Text(title.take(1))},label={Text(title)})}}}){pad->Column(Modifier.fillMaxSize().padding(pad)){Text("MoneyFamily",style=MaterialTheme.typography.headlineSmall,modifier=Modifier.padding(16.dp));when(tab){0->Home(label,income,expense,income-expense,current,members,{month=prev(month)},{month=next(month)}){adding=true};1->History(label,current,{month=prev(month)},{month=next(month)},{editor=it}){item->list=list.filterNot{it.id==item.id};saveRecords(prefs,list);if(roomReady)scope.launch{repo.delete(item.toMovement())}};2->AnalyticsScreen(list);else->Settings(members,{n->if(n.isNotBlank()&&n.trim() !in members){members+=n.trim();saveMembers(prefs,members)}},{n->if(members.size>1){members=members.filterNot{it==n};saveMembers(prefs,members)}})}}};if(adding||editor!=null)RecordEditor(editor,members,{adding=false;editor=null}){item->save(item);adding=false;editor=null}}}
}

@Composable private fun Home(label:String,income:Double,expense:Double,balance:Double,records:List<MoneyRecord>,members:List<String>,previous:()->Unit,next:()->Unit,add:()->Unit){LazyColumn(Modifier.fillMaxSize().padding(16.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){item{MonthSelector(label,previous,next)};item{Card(Modifier.fillMaxWidth()){Column(Modifier.padding(18.dp)){Text("Riepilogo reale",style=MaterialTheme.typography.titleMedium);Text("Entrate  ${money.format(income)}");Text("Uscite  ${money.format(expense)}");HorizontalDivider(Modifier.padding(vertical=8.dp));Text("Saldo  ${money.format(balance)}",style=MaterialTheme.typography.headlineSmall)}}};item{MonthlyChart(records)};item{Text("Uscite per categoria",style=MaterialTheme.typography.titleLarge)};items(records.filter{it.type==RecordType.EXPENSE}.groupBy{it.category}.entries.sortedByDescending{it.value.sumOf(MoneyRecord::amount)}){e->Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text(e.key);Text(money.format(e.value.sumOf(MoneyRecord::amount)))}};item{Text("Per membro",style=MaterialTheme.typography.titleLarge)};items(members){m->val i=records.filter{it.member==m&&it.type==RecordType.INCOME}.sumOf{it.amount};val e=records.filter{it.member==m&&it.type==RecordType.EXPENSE}.sumOf{it.amount};Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text(m);Text("+${money.format(i)} / -${money.format(e)}")}};item{OutlinedButton(add,Modifier.fillMaxWidth()){Text("+ Inserisci movimento")}}}}

@Composable private fun MonthlyChart(records:List<MoneyRecord>){val months=records.groupBy{it.date.substringAfterLast('/').take(4)+"/"+it.date.substringBeforeLast('/').takeLast(2)}.entries.sortedBy{it.key}.takeLast(6);if(months.isEmpty())return;Card(Modifier.fillMaxWidth()){Column(Modifier.padding(16.dp)){Text("Andamento mensile",style=MaterialTheme.typography.titleMedium);Canvas(Modifier.fillMaxWidth().height(180.dp)){val max=months.flatMap{listOf(it.value.filter{r->r.type==RecordType.INCOME}.sumOf{it.amount},it.value.filter{r->r.type==RecordType.EXPENSE}.sumOf{it.amount})}.maxOrNull()?.coerceAtLeast(1.0)?:1.0;val w=size.width/(months.size.coerceAtLeast(1));months.forEachIndexed{index,e->val inc=e.value.filter{it.type==RecordType.INCOME}.sumOf{it.amount};val out=e.value.filter{it.type==RecordType.EXPENSE}.sumOf{it.amount};val x=w*index+w/2;drawLine(Color(0xFF2E7D32),Offset(x,size.height),Offset(x,size.height-(inc/max)*size.height),strokeWidth=18f);drawLine(Color(0xFFC62828),Offset(x+22,size.height),Offset(x+22,size.height-(out/max)*size.height),strokeWidth=18f)}}};Row(horizontalArrangement=Arrangement.spacedBy(16.dp)){Text("● Entrate");Text("● Uscite")}}}

@Composable private fun History(label:String,records:List<MoneyRecord>,previous:()->Unit,next:()->Unit,edit:(MoneyRecord)->Unit,delete:(MoneyRecord)->Unit){var pending by remember{mutableStateOf<MoneyRecord?>(null)};Column(Modifier.fillMaxSize().padding(16.dp)){MonthSelector(label,previous,next);Spacer(Modifier.height(8.dp));if(records.isEmpty())Text("Nessun movimento per questo mese.")else LazyColumn(verticalArrangement=Arrangement.spacedBy(6.dp)){items(records.sortedByDescending{parseDate(it.date)?.timeInMillis?:0}){r->Card(Modifier.fillMaxWidth()){Column(Modifier.padding(12.dp)){RecordRow(r);Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.End){TextButton({edit(r)}){Text("Modifica")};TextButton({pending=r}){Text("Elimina")}}}}}}};pending?.let{r->AlertDialog(onDismissRequest={pending=null},title={Text("Eliminare il movimento?")},text={Text("${r.description.ifBlank{r.category}} — ${money.format(r.amount)}")},confirmButton={TextButton({delete(r);pending=null}){Text("Elimina")}},dismissButton={TextButton({pending=null}){Text("Annulla")}})}}}
@Composable private fun Settings(members:List<String>,add:(String)->Unit,remove:(String)->Unit){var value by remember{mutableStateOf("")};LazyColumn(Modifier.fillMaxSize().padding(16.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){item{Text("Impostazioni",style=MaterialTheme.typography.headlineSmall);Text("Membri della famiglia",style=MaterialTheme.typography.titleLarge)};items(members){m->Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text(m);if(members.size>1)TextButton({remove(m)}){Text("Rimuovi")}}};item{OutlinedTextField(value,{value=it},label={Text("Nuovo membro")},modifier=Modifier.fillMaxWidth())};item{Button({add(value);value=""},Modifier.fillMaxWidth()){Text("Aggiungi membro")}};item{Text("Dati reali storicizzati. Nessun budget preventivo.")}}}

@Composable private fun RecordEditor(record:MoneyRecord?,members:List<String>,dismiss:()->Unit,save:(MoneyRecord)->Unit){val context=LocalContext.current;var type by remember(record){mutableStateOf(record?.type?:RecordType.EXPENSE)};var amount by remember(record){mutableStateOf(record?.amount?.toString()?:"")};var category by remember(record){mutableStateOf(record?.category?:expenseCategories.first())};var description by remember(record){mutableStateOf(record?.description?:"")};var date by remember(record){mutableStateOf(record?.date?:dateFormat.format(Date()))};var member by remember(record){mutableStateOf(record?.member?:members.first())};var payment by remember(record){mutableStateOf(record?.paymentMethod?:paymentMethods.first())};AlertDialog(onDismissRequest=dismiss,title={Text(if(record==null)"Nuovo movimento" else "Modifica movimento")},text={Column(verticalArrangement=Arrangement.spacedBy(7.dp)){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(6.dp)){Button({type=RecordType.EXPENSE;category=expenseCategories.first()},Modifier.weight(1f)){Text("Uscita")};Button({type=RecordType.INCOME;category=incomeCategories.first()},Modifier.weight(1f)){Text("Entrata")}};OutlinedTextField(amount,{amount=it},label={Text("Importo (€)")},modifier=Modifier.fillMaxWidth());Choice("Categoria",category,context,if(type==RecordType.INCOME)incomeCategories else expenseCategories){category=it};Choice("Membro",member,context,members){member=it};Choice("Pagamento",payment,context,paymentMethods){payment=it};OutlinedTextField(description,{description=it},label={Text("Descrizione")},modifier=Modifier.fillMaxWidth());OutlinedButton({val c=parseDate(date)?:Calendar.getInstance();DatePickerDialog(context,{_,y,m,d->c.set(y,m,d);date=dateFormat.format(c.time)},c.get(Calendar.YEAR),c.get(Calendar.MONTH),c.get(Calendar.DAY_OF_MONTH)).show()},Modifier.fillMaxWidth()){Text("Data: $date")}}},confirmButton={TextButton(enabled=amount.replace(',','.').toDoubleOrNull()?.let{it>0}==true,onClick={save(MoneyRecord(record?.id?:System.currentTimeMillis(),type,amount.replace(',','.').toDouble(),category,description.trim(),date,member,payment))}){Text("Salva")}},dismissButton={TextButton(dismiss){Text("Annulla")}})}
@Composable private fun Choice(label:String,value:String,context:Context,options:List<String>,selected:(String)->Unit){OutlinedButton({android.app.AlertDialog.Builder(context).setTitle(label).setItems(options.toTypedArray()){_,i->selected(options[i])}.show()},Modifier.fillMaxWidth()){Text("$label: $value")}}
@Composable private fun RecordRow(r:MoneyRecord){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Column(Modifier.weight(1f)){Text(r.description.ifBlank{r.category},style=MaterialTheme.typography.titleMedium);Text("${r.category} • ${r.member} • ${r.date}");Text(if(r.type==RecordType.INCOME)"ENTRATA • ${r.paymentMethod}" else "USCITA • ${r.paymentMethod}",style=MaterialTheme.typography.bodySmall)};Text(if(r.type==RecordType.INCOME)"+${money.format(r.amount)}" else "-${money.format(r.amount)}")}}
@Composable private fun MonthSelector(label:String,previous:()->Unit,next:()->Unit){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){OutlinedButton(previous){Text("‹")};Text(label,style=MaterialTheme.typography.titleMedium,modifier=Modifier.padding(top=10.dp));OutlinedButton(next){Text("›")}}}
@Composable private fun AnalyticsScreen(records:List<MoneyRecord>){val months=records.groupBy{it.date.substringAfterLast('/').take(4)+"/"+it.date.substringBeforeLast('/').takeLast(2)}.entries.sortedBy{it.key};val totalIn=records.filter{it.type==RecordType.INCOME}.sumOf{it.amount};val totalOut=records.filter{it.type==RecordType.EXPENSE}.sumOf{it.amount};LazyColumn(Modifier.fillMaxSize().padding(16.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){item{Text("Analisi storica",style=MaterialTheme.typography.headlineSmall)};item{Card(Modifier.fillMaxWidth()){Column(Modifier.padding(16.dp)){Text("Totale storico reale");Text("Entrate ${money.format(totalIn)}");Text("Uscite ${money.format(totalOut)}");Text("Saldo ${money.format(totalIn-totalOut)}",style=MaterialTheme.typography.titleLarge)}}};item{MonthlyChart(records)};item{Text("Andamento per mese",style=MaterialTheme.typography.titleLarge)};items(months.reversed()){e->val i=e.value.filter{it.type==RecordType.INCOME}.sumOf{it.amount};val o=e.value.filter{it.type==RecordType.EXPENSE}.sumOf{it.amount};Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text(e.key);Text("+${money.format(i)} / -${money.format(o)} / ${money.format(i-o)}")}}}}
private fun prev(c:Calendar)=(c.clone() as Calendar).apply{add(Calendar.MONTH,-1)}
private fun next(c:Calendar)=(c.clone() as Calendar).apply{add(Calendar.MONTH,1)}
private fun parseDate(v:String)=runCatching{dateFormat.parse(v)?.let{Calendar.getInstance().apply{time=it}}}.getOrNull()
private fun sameMonth(v:String,m:Calendar):Boolean{val d=parseDate(v)?:return false;return d.get(Calendar.YEAR)==m.get(Calendar.YEAR)&&d.get(Calendar.MONTH)==m.get(Calendar.MONTH)}
private fun MoneyRecord.toMovement()=Movement(id,if(type==RecordType.INCOME)MovementType.INCOME else MovementType.EXPENSE,amount,category,description,date,member,paymentMethod)
private fun Movement.toUi()=MoneyRecord(id,if(type==MovementType.INCOME)RecordType.INCOME else RecordType.EXPENSE,amount,category,description,date,member,paymentMethod)
private fun loadRecords(p:android.content.SharedPreferences):List<MoneyRecord>=runCatching{val a=JSONArray(p.getString(RECORDS,"[]"));List(a.length()){val o=a.getJSONObject(it);MoneyRecord(o.getLong("id"),if(o.optString("type")=="INCOME")RecordType.INCOME else RecordType.EXPENSE,o.getDouble("amount"),o.optString("category","Altro"),o.optString("description"),o.optString("date",dateFormat.format(Date())),o.optString("member","Famiglia"),o.optString("paymentMethod","Carta"))}}.getOrDefault(emptyList())
private fun saveRecords(p:android.content.SharedPreferences,l:List<MoneyRecord>){val a=JSONArray();l.forEach{r->a.put(JSONObject().apply{put("id",r.id);put("type",r.type.name);put("amount",r.amount);put("category",r.category);put("description",r.description);put("date",r.date);put("member",r.member);put("paymentMethod",r.paymentMethod)})};p.edit().putString(RECORDS,a.toString()).apply()}
private fun loadMembers(p:android.content.SharedPreferences):List<String>=runCatching{val a=JSONArray(p.getString(MEMBERS,"[]"));List(a.length()){a.getString(it)}}.getOrDefault(emptyList())
private fun saveMembers(p:android.content.SharedPreferences,l:List<String>){val a=JSONArray();l.forEach(a::put);p.edit().putString(MEMBERS,a.toString()).apply()}